# Generated by Django 6.0.3 on 2026-09-28 15:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickupCounter",
            fields=[
                ("business_date", models.DateField(primary_key=True, serialize=False)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
            ],
            options={
                "ordering": ["weekday", "opens_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("closes_at__gt", models.F("opens_at"))),
                        name="hours_close_after_open",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__lte", 6)), name="hours_valid_weekday"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "availability",
                    models.CharField(
                        choices=[("available", "供應中"), ("sold_out", "已售完")],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("guidance", models.TextField(blank=True, max_length=1000)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="ordering.category",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderingSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(default="TWD", max_length=3)),
                ("accepts_dine_in", models.BooleanField(default=True)),
                ("accepts_takeout", models.BooleanField(default=True)),
                ("last_order_minutes_before_close", models.PositiveIntegerField(default=0)),
                ("agenrena_short_id", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="one_ordering_settings"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_mode",
                    models.CharField(
                        choices=[("dine_in", "內用"), ("takeout", "外帶")], max_length=16
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("pickup_code", models.CharField(blank=True, max_length=8)),
                ("business_date", models.DateField()),
                ("access_token", models.CharField(editable=False, max_length=64, unique=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tabs",
                        to="core.customeridentity",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tabs",
                        to="ordering.table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待確認"),
                            ("confirmed", "製作中"),
                            ("completed", "已完成"),
                            ("rejected", "店家未接單"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        choices=[("customer", "顧客"), ("agent", "Agent"), ("staff", "店家")],
                        max_length=16,
                    ),
                ),
                ("customer_note", models.CharField(blank=True, max_length=200)),
                ("shop_message", models.CharField(blank=True, max_length=500)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="ordering.tab",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("items", models.JSONField()),
                ("customer_note", models.CharField(blank=True, max_length=200)),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_drafts",
                        to="core.customeridentity",
                    ),
                ),
                (
                    "submitted_tab",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_draft",
                        to="ordering.tab",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_lines",
                        to="ordering.menuitem",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ordering.round",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)), name="line_quantity_positive"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tab",
            index=models.Index(fields=["business_date"], name="ordering_ta_busines_00d1aa_idx"),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True), ("table__isnull", False)),
                fields=("table",),
                name="one_open_tab_per_table",
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pickup_code", ""), _negated=True),
                fields=("business_date", "pickup_code"),
                name="pickup_code_unique_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("service_mode", "dine_in"), ("table__isnull", False)),
                    models.Q(("service_mode", "takeout"), ("table__isnull", True)),
                    _connector="OR",
                ),
                name="tab_table_matches_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_mode", "dine_in"),
                    models.Q(("phone", ""), _negated=True),
                    _connector="OR",
                ),
                name="takeout_needs_phone",
            ),
        ),
    ]
