# Generated by Django 6.0.3 on 2026-09-28 19:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0002_ordering_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderingsettings",
            name="orders_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderingsettings",
            name="pause_reason",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="orderingsettings",
            name="paused_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("min_select", models.PositiveSmallIntegerField(default=0)),
                ("max_select", models.PositiveSmallIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_select__gte", 1), ("max_select__gte", models.F("min_select"))
                        ),
                        name="option_group_select_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=60)),
                ("price_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="ordering.optiongroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="option_groups",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="ordering.optiongroup"
            ),
        ),
        migrations.CreateModel(
            name="RoundItemChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("group_name", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=60)),
                ("price_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="ordering.rounditem",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_choices",
                        to="ordering.option",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="option",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="option_name_unique_per_group"
            ),
        ),
    ]
