# Generated by Django 6.0.3 on 2026-10-01 20:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0003_options_and_pause"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.FileField(upload_to="menu/")),
                ("thumbnail", models.FileField(upload_to="menu/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("focal_x", models.PositiveSmallIntegerField(default=50)),
                ("focal_y", models.PositiveSmallIntegerField(default=50)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="ordering.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
