# Generated by Django 6.0.3 on 2026-09-28 14:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.branding
import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPermission",
            fields=[
                ("code", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(
                        choices=[("business", "商家公開資料"), ("customer", "當前顧客")],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope__in", ["business", "customer"])),
                        name="valid_agent_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRole",
            fields=[
                ("code", models.SlugField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=120)),
                ("permissions", models.ManyToManyField(to="core.agentpermission")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AgentKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(max_length=80)),
                ("prefix", models.CharField(max_length=12)),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agentrole"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "software_name",
                    models.CharField(default=core.branding.initial_software_name, max_length=120),
                ),
                ("name", models.CharField(default="我的商家", max_length=120)),
                ("about", models.TextField(blank=True, max_length=2000)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Taipei",
                        max_length=64,
                        validators=[core.models.valid_timezone],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="one_business")
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                (
                    "agenrena_customer_ref",
                    models.CharField(blank=True, max_length=36, null=True, unique=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("agenrena_customer_ref__isnull", True),
                            models.Q(("agenrena_customer_ref", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="identity_reference_not_empty",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_type", models.CharField(max_length=12)),
                ("actor_id", models.CharField(max_length=150)),
                ("actor_label", models.CharField(max_length=150)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=150)),
                ("detail", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.customeridentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgenrenaConnection",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待授權"),
                            ("connected", "已連接"),
                            ("revoked", "已失效"),
                        ],
                        max_length=12,
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("session_expires_at", models.DateTimeField(blank=True, null=True)),
                ("grant_id", models.CharField(blank=True, max_length=64)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="one_agenrena_connection"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "connected", "revoked"])),
                        name="valid_agenrena_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "擁有者"), ("admin", "管理員")],
                        default="admin",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["owner", "admin"])),
                        name="valid_human_role",
                    )
                ],
            },
        ),
    ]
